### ISSUE TITLE
Canadian Flag is Black

### ISSUE THREAD

**Issue by ValentinaManferrari** [karansher/computer-graphics-mass-spring-systems#4]
Hello! 
Does anyone know why my flag looks like in the screenshot below? I think my functions are working ok because the flag is somewhat bending toward the ground but it is hard to tell... could it be a problem from the source code? Is anyone else having this problem?
Thanks in advance!
![image](https://user-images.githubusercontent.com/57778780/206052687-6d08df5d-b201-4649-ae7a-b3c24eb89673.png)

**Comment by JanardanS** [comment]
press L and then it should hide all the dots

**Comment by ValentinaManferrari** [comment]
Thank you that worked!
