### ISSUE TITLE
Confusion about pinned vertices

### ISSUE THREAD

**Issue by OneAutumnRain** [karansher/computer-graphics-mass-spring-systems#5]
I am having some trouble with the pinned vertices part of the assignment. What exactly are the quadratic and linear penalty terms? The tutorial slides say they are the first and second RHS terms of the derivative respectively, however these are traces of matrices (and therefore doubles), so I am unsure how I can add them to Q and b when these are matrices.

**Comment by calebxcaleb** [comment]
I am having the same issue. Does anyone know what we are supposed to do?

**Comment by romanZupancic** [comment]
I think the assignment expects you to derive it yourself.

**These are the additional energy terms that actually pin the vertices in the simulation:**
![image](https://user-images.githubusercontent.com/33498090/206757561-3d6721a7-6584-43ae-8037-c82194d703ae.png)

**This is the energy equation without those vertex pinning terms**:
![image](https://user-images.githubusercontent.com/33498090/206757795-033c69b4-a0ed-488b-913b-2d3891e3e156.png)

**And this is the minimization of that energy equation without the pinning terms**:
![image](https://user-images.githubusercontent.com/33498090/206757910-1be4d3cb-9f1c-4cbc-80e9-3a56c45d2615.png)

**Notice that the solution to that minimization is those term's derivatives (i.e. the derivative of the equation in argmin) equal to 0. Especially notice that the trace operator is completely removed by the derivative:**
![image](https://user-images.githubusercontent.com/33498090/206758291-116ccc0d-e0ee-4d3a-a15d-701d17b0f40d.png)

All we need to do is come up with a minimization of an altered energy equation that includes the pinning terms (i.e. repeat the minimization and derivation with the new terms included).

**Comment by OneAutumnRain** [comment]
You just saved a man drowning for 6 hours straight with that beautiful explanation. Thank you for that!
